---
# tasks file for xrootd.role

- include: xrootd_dep.yml

- name: install XRootD packages
  yum: pkg={{ item }} state=present
  with_items:
    - xrootd-client
    - xrootd-client-devel
    - xrootd-client-libs
    - xrootd-devel
    - xrootd-doc
    - xrootd-fuse
    - xrootd-libs
    - xrootd-private-devel
    - xrootd-python
    - xrootd-selinux
    - xrootd-server
    - xrootd-server-devel
    - xrootd-server-libs
    - xrootd
 