
---

# file: site.yml

- hosts: all
  tags: environment
  become: true
  roles:
    - env.role
  vars:
     user_name: esindril
     grp_name: c3

- hosts: all
  tags: xrootd
  become: true
  roles:
    - xrootd.role
  vars:
     user_name: esindril
     grp_name: c3

- hosts: all
  tags: eos_dep
  become: true
  roles:
    - eos_dependencies.role
  vars:
     user_name: esindril
     grp_name: c3

- hosts: all
  tags: eos_instance
  become: true
  roles:
    - eos_instance.role
  vars:
     user_name: esindril
     grp_name: c3


