
---

# file: site.yml

- hosts: all
  tags: environment
  become: true
  roles:
    - env.role
  vars:
     user_name: esindril
     grp_name: c3

- hosts: all
  tags: xrootd
  become: true
  roles:
    - xrootd.role
  vars:
     user_name: esindril
     grp_name: c3

- hosts: all
  tags: eos
  become: true
  roles:
    - eos.role
  vars:
     user_name: esindril
     grp_name: c3


