---

# file roles/redis/vars/main.yml

# Configuration for individual Redis instances
instances:
  -
    name: "inst1"
    host: 127.0.0.1
    port: 6380
    weight: 1
  -
    name: "inst2"
    host: 127.0.0.1
    port: 6381
    weight: 1
  -
    name: "inst3"
    host: 127.0.0.1
    port: 6382
    weight: 1

# Configuration for nutcracker service
nutcracker_user: root
nutcracker_port: 22121
nutcracker_host: 127.0.0.1
nutcracker_logfile: /var/log/nutcracker.log
# Log level is between 0 and 11 with default 5. To work nutcracker needs to
# be build with: ./configure --enable-debug=full
nutcracker_loglevel: 10
