---

# file: roles/eosdev/tasks/git.yml

- name: install git
  yum: pkg={{ item }} state=present
  with_items:
    - git
    - gitk

# Add the global git configuration file
- name: configure git
  copy: src=gitconfig dest="/home/{{ user_name }}/.gitconfig"
        owner="{{ user_name }}" group="{{ grp_name }}" mode=0644
