---

# file: git.yml

- name: install git
  yum: pkg={{ item }} state=present
  with_items:
    - git
    - gitk

- name: configure git
  copy: src=gitconfig dest="/home/{{ user_name }}/.gitconfig"
        owner="{{ user_name }}" group="{{ grp_name }}" mode=0644
